version: 0.2

phases: 
  install:
    commands:
      - echo Installing stuff
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - ./node_modules/.bin/mocha --exit
  post_build:
    commands:
      - echo Build _completed_ at `date`
artifacts:
  files:
    - app.js
    - bin/*
    - node_modules/**/*
    - package.json
    - routes/**/*
    - test/**/*
