version: 0.2

phases: 
  install:
    commands:
      - echo Installing stuff
      - npm install -g mocha
    pre_build:
      commands: 
        - echo Installing deps
        - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run tests  
