version: 0.2

phases: 
  install:
    commands:
      - echo Installing stuff
      - npm install -g mocha
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - mocha 
